## Synology Reverse Proxy mod:
#### https://github.com/orobardet/dsm-reverse-proxy-websocket

homeassistant: 
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 141
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include config/customize.yaml
  packages: !include_dir_named packages
intent_script: !include config/intent_script.yaml
frontend:
config:
http: !include config/http.yaml
updater:
conversation:
weather: !include config/weather.yaml
history: !include config/history.yaml
recorder: !include config/recorder.yaml
influxdb: !include config/influxdb.yaml
logbook: !include config/logbook.yaml
sun:
history_graph: !include config/histroy_graph.yaml
python_script:
sensor default: !include config/sensor_default.yaml
sensor mqtt: !include config/sensor_mqtt.yaml
sensor statistics: !include config/sensor_statistics.yaml
alert: !include config/alert.yaml
binary_sensor: !include config/binary_sensor_default.yaml
tts: !include config/tts.yaml
remote: !include config/remote.yaml
emulated_hue: !include config/emulated_hue.yaml
light mqtt: !include config/light_mqtt.yaml
light other: !include config/light_default.yaml
hue: !include config/hue.yaml
ios: !include config/ios.yaml
vacuum: !include config/vaccum.yaml
mqtt: !include config/mqtt.yaml
notify: !include config/notify.yaml
input_boolean: !include config/input_boolean.yaml
device_tracker: !include config/device_tracker.yaml
media_player: !include config/media_player.yaml
xiaomi_aqara: !include config/xiaomi_aqara.yaml

group: !include groups.yaml
automation: !include_dir_merge_list automation
scene: !include scene.yaml
script: !include script.yaml