resources:
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module
  - url: /local/mini-graph-card-bundle.js?v=0.5.0
    type: module
  - url: /local/custom-lovelace/weather-card/weather-card.js
    type: module

title: Home
views:
  - !include lovelace/0-home.yaml
  - !include lovelace/10-people.yaml
  #- !include lovelace/2-livingroom.yaml
  #- !include lovelace/30-bedroom.yaml
  - !include lovelace/4-0-temperature.yaml
  #- !include lovelace/50-plants.yaml
  #- !include lovelace/60-music.yaml
  - !include lovelace/70-candy.yaml
  - !include lovelace/75-grill.yaml
  - !include lovelace/8-car.yaml
      
