input_boolean:
  lvn_scene_morninglight:
    name: Szene Morgen
  lvn_scene_cooking:
    name: Szene Kochen
  lvn_scene_music:
    name: Szene Musik
  lvn_scene_tv:
    name: Szene TV
  lvn_scene_cosy:
    name: Szene Entspannen
  lvn_scene_nightlight:
    name: Szene Nachtlicht
  lvn_scene_eat:
    name: Szene Essen
  lvn_scene_off:
    name: Szene Aus

automation:
  - id: lvn_scene_button_status_morninglight
    alias: lvn_scene_button_status_morninglight
    trigger:
      - platform: state
        entity_id: input_text.lvn_selectedscene
        to: 'Morgen'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.lvn_scene_morninglight
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_cooking
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_music
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_tv
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_cosy
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_nightlight
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_eat
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_off
  - id: lvn_scene_button_status_cooking
    alias: lvn_scene_button_status_cooking
    trigger:
      - platform: state
        entity_id: input_text.lvn_selectedscene
        to: 'Kochen'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_morninglight
      - service: input_boolean.turn_on
        entity_id: input_boolean.lvn_scene_cooking
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_music
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_tv
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_cosy
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_nightlight
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_eat
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_off
  - id: lvn_scene_button_status_music
    alias: lvn_scene_button_status_music
    trigger:
      - platform: state
        entity_id: input_text.lvn_selectedscene
        to: 'Musik'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_morninglight
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_cooking
      - service: input_boolean.turn_on
        entity_id: input_boolean.lvn_scene_music
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_tv
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_cosy
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_nightlight
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_eat
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_off
  - id: lvn_scene_button_status_tv
    alias: lvn_scene_button_status_tv
    trigger:
      - platform: state
        entity_id: input_text.lvn_selectedscene
        to: 'Fernsehen'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_morninglight
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_cooking
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_music
      - service: input_boolean.turn_on
        entity_id: input_boolean.lvn_scene_tv
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_cosy
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_nightlight
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_eat
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_off
  - id: lvn_scene_button_status_cosy
    alias: lvn_scene_button_status_cosy
    trigger:
      - platform: state
        entity_id: input_text.lvn_selectedscene
        to: 'Entspannen'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_morninglight
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_cooking
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_music
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_tv
      - service: input_boolean.turn_on
        entity_id: input_boolean.lvn_scene_cosy
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_nightlight
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_eat
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_off
  - id: lvn_scene_button_status_nightlight
    alias: lvn_scene_button_status_nightlight
    trigger:
      - platform: state
        entity_id: input_text.lvn_selectedscene
        to: 'Nachtlicht'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_morninglight
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_cooking
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_music
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_tv
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_cosy
      - service: input_boolean.turn_on
        entity_id: input_boolean.lvn_scene_nightlight
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_eat
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_off
  - id: lvn_scene_button_status_eat
    alias: lvn_scene_button_status_eat
    trigger:
      - platform: state
        entity_id: input_text.lvn_selectedscene
        to: 'Essen'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_morninglight
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_cooking
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_music
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_tv
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_cosy
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_nightlight
      - service: input_boolean.turn_on
        entity_id: input_boolean.lvn_scene_eat
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_off
  - id: lvn_scene_button_status_off
    alias: lvn_scene_button_status_off
    trigger:
      - platform: state
        entity_id: input_text.lvn_selectedscene
        to: 'Aus'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_morninglight
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_cooking
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_music
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_tv
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_cosy
      - service: input_boolean.turn_off
        entity_id: input_boolean.lvn_scene_nightlight
      - service: input_boolean.turn_on
        entity_id: input_boolean.lvn_scene_off
        

    