default_view1:
  view: yes
  name: Home
  icon: mdi:home-variant
  entities:
    - group.time
    - device_tracker.mobile_adriana
    - device_tracker.mobile_christian
    - group.windows
    - group.bedlight
    - group.lvn_lights
    - group.vacuum
    - group.temperatures
    - group.humidity
    - media_player.spotify
    - weather.wetter
livingroom_view:
  view: yes
  name: Wohnzimmer
  icon: mdi:sofa
  entities:
    - group.lvn_lights
    - group.living_sensor
    - group.living_fenster
    - group.vacuum
    - remote.harmony
    - binary_sensor.motion_sensor_livingroom
bedroom_view:
  view: yes
  name: Schlafzimmer
  icon: mdi:seat-individual-suite
  entities:
    - group.bedlight
    - group.bedroom_windows
    - binary_sensor.motion_sensor_bedroom
    - group.alarm_adriana
    - group.bedroom_light
guest_view:
  view: yes
  name: Gästezimmer
  icon: mdi:printer
  entities:
    - light.gst_desk
    - group.raspberry
temperature_view:
  view: yes
  name: Temperaturen
  icon: mdi:thermometer
  entities:
    - group.temperatures
    - group.humidity
    - group.pressure
    - history_graph.temperature
    - history_graph.humidity
plant_view:
  view: yes
  name: Pflanzen
  icon: mdi:leaf
  entities:
    - group.flower_care_1
    - group.flower_care_2
    - group.plant_watering
nerd_view:
  view: yes
  name: Info
  icon: mdi:candycane
  entities:
    - group.all_automations
    - group.all_scripts
    - group.all_switches
    - group.all_lights
    - sensor.illumination_xiaomi_gateway
    - light.gateway_light_1
    - group.time
    - group.all_devices
    - light.test_mqtt_light
lvn_couchArea_sensor:
  name: Wohnzimmer Sensoren
  entities:
    - timer.livingroom_nightlight
bedroom_light:
  name: Schlafzimmer Licht
  entities:
    - light.bdr_nightstand_adriana
    - light.bdr_nightstand_christian
vacuum:
  name: Staubsauger
  entities:
    - input_boolean.staubi_waiting
    - vacuum.staubi
iphone_cm:
  name: iPhone Christian
  entities:
    - sensor.phone_von_christian_battery_level
    - sensor.phone_von_christian_battery_state
#flower_care_1:
#  name: Zitrone
#  entities:
#    - sensor.flower_care_1_moisture
#    - sensor.flower_care_1_fertility
#    - sensor.flower_care_1_temperature
#    - sensor.flower_care_1_batteryLevel
#    - sensor.flower_care_1_lux
#    - sensor.flower_care_1_battery
#    - sensor.flower_care_1_state
flower_care_2:
  name: Palme
  entities:
    - sensor.flower_care_2_moisture
    - sensor.flower_care_2_fertility
    - sensor.flower_care_2_temperature
    - sensor.flower_care_2_batteryLevel
    - sensor.flower_care_2_lux
    - sensor.flower_care_2_battery
    - sensor.flower_care_2_state
windows:
  name: Fenster
  entities:
    - binary_sensor.door_balcony
    - binary_sensor.window_kitchen
    - binary_sensor.window_bath_normal
    - binary_sensor.window_bath_roof
    - binary_sensor.window_bed_right
    - binary_sensor.window_bed_left
    - binary_sensor.window_guest_roof
    - binary_sensor.window_guest_normal
lvn_couchArea_windows:
  name: "Fenster Wohnzimmer"
  entities:
    - binary_sensor.window_kitchen
    - binary_sensor.door_balcony
bedroom_windows:
  name: "Fenster Schlafzimmer"
  entities:
    - binary_sensor.window_bed_right
    - binary_sensor.window_bed_left