graph_temp:
  name: temperature
  entities:
    - sensor.temperature_corridor
    - sensor.temperature_bath
    - sensor.temperature_bedroom
    - sensor.temperature_cubby
    - sensor.temperature_guest
graph_humidity:
  name: humidity
  entities:
    - sensor.humidity_bath
    - sensor.humidity_bedroom
    - sensor.humidity_corridor
    - sensor.humidity_cubby
    - sensor.humidity_guest