- name: GuestMove
  entities:
    light.schreibtischlampe: on
- name: GuestOff
  entities:
    light.schreibtischlampe: off
- name: bed_preparation
  entities:
    light.lvn_displayCase: off
    light.lvn_sideboard: on
    light.lvn_rgbCouchArea:
      rgb_color: [170,79,0]
    light.bett: on
- name: tv
  entities:
    light.lvn_displayCase: on
    light.lvn_sideboard: on
    light.lvn_diningTable: off
    light.lvn_couchArea: off
    light.lvn_rgbCouchArea:
      state: on
      rgb_color: [255,139,12]
      brightness: 190
    remote.harmony:
      state: on
      activity: 17652505
- name: eat
  entities:
    light.lvn_displayCase: on
    light.lvn_sideboard: on
    light.lvn_diningTable: off
    light.lvn_couchArea: off
    light.lvn_rgbCouchArea:
      state: on
      rgb_color: [255,139,12]
      brightness: 190
- name: allOff
  entities:
    light.lvn_displayCase: off
    light.lvn_sideboard: off
    light.lvn_diningTable: off
    light.lvn_couchArea: off
    remote.harmony: off
    light.lvn_rgbCouchArea: off
    light.bed: off
    light.schreibtischlampe: off
    light.nightstand_adriana: off
    light.nightstand_christian: off
- name: clean
  entities:
    light.lvn_displayCase: on
    light.lvn_sideboard: on
    light.lvn_diningTable: on
    light.lvn_couchArea: on
    remote.harmony:
      state: on
      activity: 18715284
    light.lvn_rgbCouchArea: on
    light.bed: on
    light.schreibtischlampe: on
    light.nightstand_adriana: on
    light.nightstand_christian: on
- name: cooking
  entities:
    light.lvn_displayCase: on
    light.lvn_sideboard: on
    light.lvn_diningTable: on
    light.lvn_couchArea: on
    remote.harmony:
      state: on
      activity: 18715284
    light.lvn_rgbCouchArea: on
    light.bed: off
    light.schreibtischlampe: off
    light.nightstand_adriana: off
    light.nightstand_christian: off
  

