- platform: time_date
  display_options:
    - 'date_time'
- platform: yr
- platform: waze_travel_time
  origin: !secret address_home
  destination: !secret address_work_christian
  name: 'home - evoila'
  region: 'EU'
- platform: waze_travel_time
  origin: !secret address_work_christian
  destination: !secret address_home
  name: 'evoila - home'
  region: 'EU'
- platform: darksky
  api_key: !secret darksky_key
  update_interval: '00:15:00'
  language: de
  monitored_conditions:
    - summary
    - temperature
    - precip_type
    - precip_intensity
    - precip_probability
    - precip_accumulation
    - daily_summary
    - apparent_temperature
    - humidity
    - wind_speed
    - wind_bearing
    - pressure
    - icon
    - hourly_summary