midnight:
    # Main colors
    primary-color: '#5294E2'                                                        # Header
    accent-color: '#E45E65'                                                         # Accent color
    dark-primary-color: 'var(--accent-color)'                                       # Hyperlinks                                         
    light-primary-color: 'var(--accent-color)'                                      # Horizontal line in about
                                                                                 
    # Text colors                                                                  
    primary-text-color: '#299365'                                                   # Primary text colour, here is referencing dark-primary-color
    text-primary-color: 'var(--primary-text-color)'                                 # Primary text colour
    secondary-text-color: '#5294E2'                                                 # For secondary titles in more info boxes etc.
    disabled-text-color: '#7F848E'                                                  # Disabled text colour
    label-badge-border-color: 'green'                                               # Label badge border, just a reference value   
    
    # Background colors                                                            
    primary-background-color: '#383C45'                                             # Settings background
    secondary-background-color: '#383C45'                                           # Main card UI background  
    divider-color: 'rgba(0, 0, 0, .12)'                                             # Divider 
      
    # Table rows                                                                   
    table-row-background-color: '#353840'                                           # Table row
    table-row-alternative-background-color: '#3E424B'                               # Table row alternative
                                                                                 
    # Nav Menu                                                                   
    paper-listbox-color: 'var(--primary-color)'                                     # Navigation menu selection hoover
    paper-listbox-background-color: '#2E333A'                                       # Navigation menu background
    paper-grey-50: 'var(--primary-text-color)'                                   
    paper-grey-200: '#414A59'                                                       # Navigation menu selection
                                                                                 
    # Paper card                                                               
    paper-card-header-color: 'var(--accent-color)'                                  # Card header text colour
    paper-card-background-color: '#434954'                                          # Card background colour
    paper-dialog-background-color: '#434954'                                        # Card dialog background colour
    paper-item-icon-color: 'var(--primary-text-color)'                              # Icon color
    paper-item-icon-active-color: '#F9C536'                                         # Icon color active
    paper-item-icon_-_color: 'green'           
    paper-item-selected_-_background-color: '#434954'                               # Popup item select                      
    paper-tabs-selection-bar-color: 'green'
    
    # Labels 
    label-badge-red: 'var(--accent-color)'                                          # References the brand colour label badge border
    label-badge-text-color: 'var(--primary-text-color)'                             # Now same as label badge border but that's a matter of taste
    label-badge-background-color: '#2E333A'                                         # Same, but can also be set to transparent here
    
    # Switches
    paper-toggle-button-checked-button-color: 'var(--accent-color)'
    paper-toggle-button-checked-bar-color: 'var(--accent-color)'
    paper-toggle-button-checked-ink-color: 'var(--accent-color)'
    paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
    paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
    paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'  
    
    # Sliders
    paper-slider-knob-color: 'var(--accent-color)'
    paper-slider-knob-start-color: 'var(--accent-color)'
    paper-slider-pin-color: 'var(--accent-color)'
    paper-slider-active-color: 'var(--accent-color)'
    paper-slider-container-color: 'linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat'
    paper-slider-secondary-color: 'var(--secondary-background-color)'
    paper-slider-disabled-active-color: 'var(--disabled-text-color)'
    paper-slider-disabled-secondary-color: 'var(--disabled-text-color)'
    
    # Google colors
    google-red-500: '#E45E65'
    google-green-500: '#39E949'
material_dark_green:
  light_green: "#2c6b52" #"#08a8a5"
  dark_green: "#2c5b48" #"#017775"
  dark_grey: "#232326"
  light_grey: "#344249"

  red: "#681111"
  yellow: "#bcb90d"
  white: "#979797"
  pink: "#7a1d52"

#Top bar, activate text on script, selected icon on home assistant menu, top panel of media players, text in config page, text on developer tools states page, mqtt publish text, logbook text
  primary-color: "var(--light_green)"
# divider on dev tools info page
  light-primary-color: "var(--red)"
# some hyperlinked text
  dark-primary-color: "var(--red)"
# not sure where used
  text-primary-color: "var(--pink)"
# main background, top of side panel
  primary-background-color: "var(--dark_grey)"
# not sure where used 
  sidebar-text_-_background: "var(--pink)"
# card background colour, part of media player background
  paper-card-background-color: "var(--light_grey)"
# mqtt pubish header and thats it 
  paper-card-header-color: "var(--white)"
# main background colour of states page
  secondary-background-color: "var(--dark_grey)"
# most of the text used
  primary-text-color: "var(--white)"
#secondary pieces of text 
  secondary-text-color: "var(--white)"
#main background of side panel 
  paper-listbox-background-color: "var(--light_grey)"
#not sure where used
  paper-toggle-button-checked-ink-color: "var(--pink)"
#switch colour when on
  paper-toggle-button-checked-button-color: "var(--yellow)"
#Backgroud of switch/toggle when on
  paper-toggle-button-checked-bar-color: "var(--yellow)"
#slide knob on brightness/volumes when not 0
  paper-slider-knob-color: "var(--yellow)"
#slide knob on brightness/volumes when 0
  paper-slider-knob-start-color: "var(--red)"
#don't know where used
  paper-slider-pin-color: "var(--pink)"
#colour of brightness/volume slider line in used portion 
  paper-slider-active-color: "var(--yellow)"
#not sure where used
  paper-slider-secondary-color: "var(--pink)"
# background of brightness/volume slider line not used portion 
  paper-slider-container-color: "var(--red)"
#not sure where used
  paper-progress-secondary-color: "var(--pink)"
#background of theme selection toggle tiny use 
  paper-item-selected_-_background-color: "var(--light_green)"
#text, not sure which one "var(--white)"
  paper-item-icon_-_color: "var(--pink)"
# icon on state page when off
  paper-item-icon-color: "var(--dark_green)"
#states icon when active 
  paper-item-icon-active-color: "var(--yellow)"
#colour of switch toggle when off, icon on selected page of menu 
  paper-grey-50: "var(--light_green)"
#background of selected screen on menu "var(--light_green)"
  paper-grey-200: "var(--dark_green)"
#Backgound of label icon
  label-badge-background-color: "var(--light_grey)"
#colour of text in label icon 
  label-badge-text-color: "var(--white)"
#colour of edge of sensor labels
  label-badge-red: "var(--red)"
#not sure where used
  label-badge-blue: "var(--pink)"
  label-badge-green: "var(--pink)"
  label-badge-yellow: "var(--pink)"
  label-badge-grey: "var(--pink)"
# Row 1 on entities page
  table-row-background-color: "var(--light_grey)"
# row 2 on entities page
  table-row-alternative-background-color: "var(--dark_grey)"

PmxMononight:
  # MyVariables
  base-hue: '150' #Controls the base (and accent) color hue (0-360) | 0=Red 60=Yellow 120=Green 180=Cyan 240=Blue 300=Magenta 360=Red
  base-sat: '16%' #Controls the saturation of the theme (0%-100%) | 0%=Grey 100%=Full Saturation
  # MyVar
  huesat: 'var(--base-hue), var(--base-sat),'
  # Primary Color
  primary-color: 'hsl(var(--huesat) 20%)'
  # Backgrounds
  primary-background-color: 'var(--primary-color)'
  secondary-background-color: 'hsl(var(--huesat) 16%)'
  paper-listbox-background-color: 'var(--primary-color)'
  paper-card-background-color: 'hsl(var(--huesat) 12%)'
  paper-dialog-background-color: 'var(--paper-card-background-color)'
  table-row-background-color: 'hsl(var(--huesat) 12%)'
  table-row-alternative-background-color: 'hsl(var(--huesat) 10%)'
  # Devider
  divider-color: 'hsla(0, 0%, 0%, 0)'
  dark-divider-opacity: '0'
  light-divider-opacity: '0'
  # Text colors
  primary-text-color: 'hsl(var(--huesat) 60%)'
  text-primary-color: 'hsl(var(--huesat) 60%)'
  secondary-text-color: 'hsl(var(--huesat) 60%)'
  disabled-text-color: 'hsl(var(--huesat) 70%)'
  sidebar-text_-_color: 'hsl(var(--huesat) 90%)'
  sidebar-text-color: 'hsl(var(--huesat) 90%)'
  paper-card-header-color: 'hsl(var(--base-hue), 90%, 50%)'
  # Text Adjustments
  paper-font-headline_-_letter-spacing: '-0.5px'
  paper-font-headline_-_font-weight: '500'
  paper-font-body1_-_font-weight: '500'
  # Nav Menu
  paper-listbox-color: 'hsl(var(--huesat) 50%)'
  paper-grey-50: 'hsl(var(--huesat) 50%)'
  paper-grey-200: 'hsla(var(--huesat) 26%)'
  # Paper card
  paper-item-icon-color: 'hsl(var(--huesat) 30%)'
  paper-item-icon-active-color: 'var(--paper-item-icon-color)'
  paper-item-icon_-_color: 'var(--paper-item-icon-color)'
  paper-item-selected_-_background-color: 'hsla(0, 0%, 0%, 0.2)'
  paper-tabs-selection-bar-color: 'hsla(0, 0%, 0%, 0.2)'
  # Labels
  label-badge-red: 'hsla(0, 0%, 0%, 0)'
  label-badge-border-color: 'var(--label-badge-red)'
  label-badge-background-color: 'var(--paper-card-background-color)'
  label-badge-text-color: 'var(--primary-text-color)'
  # Shadows
  shadow-elevation-2dp_-_box-shadow: 'inset 0px 0px 0px 4px hsl(var(--huesat) 18%)'
  shadow-elevation-16dp_-_box-shadow: 'inset 0px 0px 0px 4px hsl(var(--huesat) 28%)'
  # Switches
  paper-toggle-button-checked-button-color: 'hsl(var(--base-hue), 90%, 50%)'
  paper-toggle-button-checked-bar-color: 'hsl(var(--huesat) 25%)'
  paper-toggle-button-unchecked-button-color: 'hsl(var(--huesat) 25%)'
  paper-toggle-button-unchecked-bar-color: 'hsl(var(--huesat) 5%)'
  # Sliders
  paper-slider-knob-color:  'hsl(var(--base-hue), 90%, 50%)'
  paper-slider-knob-start-color: 'hsl(var(--base-hue), 80%, 25%)'
  paper-slider-pin-color:  'hsl(var(--base-hue), 90%, 50%)'
  paper-slider-active-color:  'hsl(var(--base-hue), 90%, 50%)'
  paper-slider-container-color: 'hsl(var(--huesat) 28%)'
  paper-slider-secondary-color: 'hsl(var(--huesat) 90%)'
  paper-slider-disabled-active-color: 'hsl(var(--base-hue), 80%, 25%)'
  paper-slider-disabled-secondary-color: 'hsl(var(--base-hue), 80%, 25%)'
  paper-dialog-color: 'hsl(var(--base-hue), 20%, 80%)'

dark-green:
# Main colors that can be changed
  primary-color: "#389638"
  disabled-text-color: "#545454"
  divider-color: "rgba(255, 255, 255, 0.12)"
  paper-card-background-color: "#4e4e4e"
  paper-grey-200: "#191919"
  paper-item-icon-color: "#d3d3d3"
  paper-listbox-background-color: "#202020"
  paper-listbox-color: "#FFFFFF"
  primary-background-color: "#303030"
  primary-text-color: "#cfcfcf"
  secondary-background-color: "#2b2b2b"
  secondary-text-color: "#389638"
# Colors based on variables, see above
  label-badge-background-color: "var(--secondary-background-color)"
  label-badge-text-color: "var(--text-primary-color)"
  paper-card-header-color: "var(--paper-item-icon-color)"
  paper-grey-50: "var(--primary-text-color)"
  paper-item-icon-active-color: "var(--primary-color)"
  paper-item-icon_-_color: "var(--primary-text-color)"
  paper-slider-active-color: "var(--primary-color)"
  paper-slider-knob-color: "var(--primary-color)"
  paper-slider-knob-start-color: "var(--primary-color)"
  paper-slider-pin-color: "var(--primary-color)"
  paper-slider-secondary-color: "var(--light-primary-color)"
  paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
  paper-toggle-button-checked-button-color: "var(--primary-color)"
  paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
  paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"
  label-badge-red: 'var(--primary-color)'
  sidebar-icon-color: "var(--paper-item-icon-color)"