- id: Gute Nacht Start
  alias: Schlaf Start
  action:
  - service: xiaomi_aqara.play_ringtone
    data:
      ringtone_vol: 10
      ringtone_id: 10003
  - service: light.turn_on
    entity_id: light.bett
    data:
      brightness: 190
      rgb_color:
      - 190
      - 105
      - 0
  - service: light.turn_on
    entity_id: light.wohnzimmerfarblicht
    data:
      brightness: 190
      rgb_color:
      - 190
      - 105
      - 0
  - service: media_player.play_media
    entity_id: media_player.spotify
    data:
      media_content_type: playlist
      media_content_id: 'spotify:user:spotify:playlist:37i9dQZF1DX0jgyAiPl8Af'
  - service: media_player.shuffle_set
    entity_id: media_player.spotify
    data:
      shuffle: true
  - service: media_player.media_next_track
    entity_id: media_player.spotify
  - service: media_player.select_source
    entity_id: media_player.spotify
    data:
      source: 'Christians Echo Dot'
  - service: light.turn_on
    entity_id: light.vitrinen
  - delay: 00:00:01
  - service: light.turn_on
    entity_id: light.sideboard
  - service: light.turn_on
    entity_id: light.christian_nachtlicht
  - service: light.turn_on
    entity_id: light.adri_nachtlicht
  - service: automation.turn_off
    entity_id: automation.bettlicht_an
  - service: automation.turn_off
    entity_id: automation.bettlicht_aus
  - condition:
      condition: state
      entity_id: remote.harmony
      state: on
  - service: remote.turn_on
    entity_id: remote.harmony
    data:
      #Radio: 18715284
      # FireTV
      activity: 17652505
      #Chromecast
      #24447593
  - service: media_player.select_source
    entity_id: media_player.spotify
    data:
      source: 'Amazon FireTV Stick'
  trigger:
  - platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.wall_switch_both_158d00016396b8
      click_type: both
- id: nachtboer
  alias: Gute Nacht Teddy
  action:
  - service: remote.turn_off
    entity_id: remote.harmony
  - service: media_player.media_stop
    entity_id: media_player.spotify
  - service: xiaomi_aqara.play_ringtone
    data:
      ringtone_vol: 8
      ringtone_id: 10002
  - service: light.turn_off
    entity_id: light.wohnzimmerfarblicht
  - service: light.turn_off
    entity_id: light.vitrinen
  - delay: 00:00:01
  - service: light.turn_off
    entity_id: light.sideboard
  - delay: 00:00:01
  - service: light.turn_off
    entity_id: light.christian_nachtlicht
  - delay: 00:00:01
  - service: light.turn_off
    entity_id: light.adri_nachtlicht
  - delay: 00:01:00
  - service: light.turn_off
    entity_id: light.bett
    data:
      transition: 60
  - service: automation.turn_on
    entity_id: automation.bettlicht_an
  - service: automation.turn_on
    entity_id: automation.bettlicht_aus
  trigger:
  - platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00016d732a
      click_type: long_click_press