homeassistant:
  customize:
    binary_sensor.keybox_key_1:
      friendly_name: Schl체ssel Christian
    light.keybox_rgb:
      friendly_name: Schl체sselkasten RGB

automation:
  - id: keyboxFlashButtons
    alias: Flash Keybox Buttons
    action:
      - service: python_script.keybox_button_flash
    trigger:
      - platform: state
        entity_id: binary_sensor.keybox_button2
  - id: keyboxAllOff
    alias: Keybox All Off
    action:
      - service: mqtt.publish
        data:
          topic: "tts/fhem"
          payload_template: "Es werden alle Ger채te ausgeschaltet."
          qos: "2"
      - service: light.turn_off
        entity_id: group.all_lights
      - service: remote.turn_off
        entity_id: remote.harmony
    trigger:
      - platform: state
        entity_id: binary_sensor.keybox_button1
  - id: keyboxChristianHome
    alias: Keybox Christian Home
    action:
      - service: mqtt.publish
        data:
          topic: "tts/fhem"
          payload_template: "Der Schl체ssel bitte der Herr"
          qos: "2"
      - service: light.turn_on
        entity_id: light.keybox_rgb
        data:
          rgb_color:
            - 220
            - 190
            - 90
          brightness_pct: 70
      - delay: 10
      - service: light.turn_off
        entity_id: light.keybox_rgb
    trigger:
      - entity_id: device_tracker.mobile_christian
        platform: state
        to: home
        for: 
          minutes: 2
    condition:  
      - condition: state
        entity_id: binary_sensor.keybox_key_left
        state: "off"
  - id: keyboxChristianKeyPresent
    alias: Keybox Christian key present
    action:
      - service: light.turn_on
        entity_id: light.keybox_rgb
        data:
          rgb_color:
            - 50
            - 190
            - 90
          brightness_pct: 70
      - delay: 2
      - service: light.turn_off
        entity_id: light.keybox_rgb
    trigger:
      - entity_id: binary_sensor.keybox_key_left
        platform: state
        to: "on"
        for:
          seconds: 3