telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    parse_mode: html
    allowed_chat_ids:
      - !secret telegram_chat_id_christian
      - !secret telegram_chat_id_adriana

input_boolean:
  test_telegram:
    name: Test Telegram
    icon: mdi:calendar

automation:
  - id: telegramtest
    alias: 'My Telegram test'
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: '/test2'
    action:
      - service: input_boolean.toggle
        entity_id: input_boolean.test_telegram
  - id: LightsAndMusicLeaveOffManual
    alias: 'Things on when leave - command off'
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: '/lightsAndMusicOff'
    action:
      - service: lights.turn_off
        entity_id: group.all_lights
      - service: remote.turn_off
        entity_id: remote.harmony
      - service: telegram_bot.send_message
        data:
          message: Die Geräte wurden ausgeschaltet
          title: Geräte ausgeschaltet!
          target:
            - !secret telegram_chat_id_christian
            - !secret telegram_chat_id_adriana
  - id: LightsAndMusicLeave
    alias: 'Things on when leave'
    trigger:
    - entity_id: device_tracker.mobile_adriana, device_tracker.mobile_christian
      platform: state
      to: not_home
    condition:
    - condition: and
      conditions:
      - condition: state
        entity_id: device_tracker.mobile_adriana
        state: not_home
      - condition: state
        entity_id: device_tracker.mobile_christian
        state: not_home
      - condition: state
        entity_id: group.all_lights
        state: 'on'
    action:
    - service: telegram_bot.send_message
      data:
        message: Es sind noch Lichter an oder die Musik an
        title: Geräte angelassen!
        target:
          - !secret telegram_chat_id_christian
          - !secret telegram_chat_id_adriana
        inline_keyboard:
          - 'Ausschalten:/lightsAndMusicOff'